Repository kinoplan/utils, pull requests merged in 2021-12, with the labels that each got.

#87 Update sbt-scalafmt to 2.4.5
  project/plugins.sbt
Labels: dependencies

#88 Update sbt to 1.5.6
  project/build.properties
Labels: dependencies

#84 Update sbt-scalafix to 0.9.33
  project/plugins.sbt
Labels: dependencies

#77 Update organize-imports to 0.6.0
  scalafix.sbt
Labels: dependencies

#76 Update sbt-scoverage to 1.9.2
  project/plugins.sbt
Labels: dependencies

#66 Update mockito-3-4 to 3.2.10.0
  project/Dependencies.scala
Labels: dependencies

#35 Update scala-library to 2.13.6
  .github/workflows/build.yml
  project/ProjectSettings.scala
Labels: dependencies

#65 Update scalatest to 3.2.10
  project/Dependencies.scala
Labels: dependencies

#61 Update scala-library to 2.12.15
  .github/workflows/build.yml
  project/ProjectSettings.scala
Labels: dependencies

#75 Update scala-library to 2.13.7
  .github/workflows/build.yml
  project/ProjectSettings.scala
Labels: dependencies

#89 Add zio reactivemongo & reactivemongo bson joda time
  base/reactivemongo/bson-joda-time/src/main/scala/io/kinoplan/utils/reactivemongo/bson/joda/time/BsonJodaTimeHandlers.scala
  build.sbt
  codecov.yml
  project/BaseModules.scala
  project/Dependencies.scala
  project/WrappersModules.scala
  project/ZioModules.scala
  zio/reactivemongo/src/main/scala/io/kinoplan/utils/zio/reactivemongo/api/IntegrationCheck.scala
  zio/reactivemongo/src/main/scala/io/kinoplan/utils/zio/reactivemongo/api/ReactiveMongoApi.scala
  zio/reactivemongo/src/main/scala/io/kinoplan/utils/zio/reactivemongo/api/driver/AsyncDriverResource.scala
  zio/reactivemongo/src/main/scala/io/kinoplan/utils/zio/reactivemongo/config/MongoConfig.scala
  zio/reactivemongo/src/main/scala/io/kinoplan/utils/zio/reactivemongo/daos/ReactiveMongoDaoBase.scala
  zio/reactivemongo/src/main/scala/io/kinoplan/utils/zio/reactivemongo/modules/MongoModule.scala
  zio/reactivemongo/src/main/scala/io/kinoplan/utils/zio/reactivemongo/utils/BsonHandlers.scala
  zio/reactivemongo/src/main/scala/io/kinoplan/utils/zio/reactivemongo/utils/Queries.scala
  zio/reactivemongo/src/main/scala/io/kinoplan/utils/zio/reactivemongo/utils/syntax/ReactiveMongoSyntax.scala
Labels: enhancement

#90 Update reactivemongo to 1.0.8
  project/Dependencies.scala
Labels: dependencies

#91 Add zio monitoring prometheus
  build.sbt
  project/Dependencies.scala
  project/ZioModules.scala
  zio/monitoring/prometheus/src/main/scala/io/kinoplan/utils/zio/monitoring/prometheus/config/PrometheusConfig.scala
  zio/monitoring/prometheus/src/main/scala/io/kinoplan/utils/zio/monitoring/prometheus/modules/PrometheusModule.scala
  zio/monitoring/prometheus/src/main/scala/io/kinoplan/utils/zio/monitoring/prometheus/server/PrometheusServer.scala
  zio/reactivemongo/src/main/scala/io/kinoplan/utils/zio/reactivemongo/bson/BsonHandlers.scala
  zio/reactivemongo/src/main/scala/io/kinoplan/utils/zio/reactivemongo/daos/Queries.scala
  zio/reactivemongo/src/main/scala/io/kinoplan/utils/zio/reactivemongo/daos/ReactiveMongoDaoBase.scala
  zio/reactivemongo/src/main/scala/io/kinoplan/utils/zio/reactivemongo/syntax/ReactiveMongoSyntax.scala
Labels: enhancement

#96 Update zio to 1.0.13
  project/Dependencies.scala
Labels: dependencies

#97 Update sbt to 1.5.7
  project/build.properties
Labels: dependencies

#100 Update logback-core to 1.2.8
  project/Dependencies.scala
Labels: dependencies

#103 Update reactivemongo to 1.0.9
  project/Dependencies.scala
Labels: dependencies

#105 Update reactivemongo to 1.0.10
  project/Dependencies.scala
Labels: dependencies

#106 Add uninterruptible for zio ReactiveMongoApi
  zio/reactivemongo/src/main/scala/io/kinoplan/utils/zio/reactivemongo/api/ReactiveMongoApi.scala
Labels: bug

#107 Update sbt to 1.5.8
  project/build.properties
Labels: dependencies

#109 Update logback-classic, logback-core to 1.2.10
  project/Dependencies.scala
Labels: dependencies

#111 Update sbt-scalafmt to 2.4.6
  project/plugins.sbt
Labels: dependencies

#113 Update sbt to 1.6.0
  project/build.properties
Labels: dependencies

#112 Update scalafmt-core to 3.3.0
  .scalafmt.conf
  base/scala-logging/src/test/scala/io/kinoplan/utils/scala/logging/LoggableSpec.scala
  base/scala-logging/src/test/scala/io/kinoplan/utils/scala/logging/LoggerSpec.scala
  base/scala-logging/src/test/scala/io/kinoplan/utils/scala/logging/LoggerWithBasicMDCSpec.scala
  base/scala-logging/src/test/scala/io/kinoplan/utils/scala/logging/LoggerWithEmptyMDCSpec.scala
  base/scala-logging/src/test/scala/io/kinoplan/utils/scala/logging/LoggerWithLogbackMDCSpec.scala
  base/scala-logging/src/test/scala/io/kinoplan/utils/scala/logging/context/MapContextSpec.scala
  implicits/boolean/src/test/scala/io/kinoplan/utils/implicits/BooleanSyntaxSpec.scala
  implicits/collection/src/test/scala/io/kinoplan/utils/implicits/CollectionSyntaxSpec.scala
  project/Dependencies.scala
  zio/reactivemongo/src/main/scala/io/kinoplan/utils/zio/reactivemongo/modules/MongoModule.scala
Labels: dependencies

#114 Update sbt to 1.6.1
  project/build.properties
Labels: dependencies
