Repository kinoplan/utils, pull requests merged in 2022-10, with the labels that each got.

#231 Update play to 2.8.18
  project/Dependencies.scala
Labels: dependencies

#233 Update joda-time to 2.11.2
  project/Dependencies.scala
Labels: dependencies

#226 Update scala-library to 2.12.17
  .github/workflows/build.yml
  project/ProjectSettings.scala
Labels: dependencies

#236 Update scalactic to 3.2.14
  project/Dependencies.scala
Labels: dependencies

#235 Update sbt to 1.7.2
  project/build.properties
Labels: dependencies

#238 Update scalatest to 3.2.14
  project/Dependencies.scala
Labels: dependencies

#239 Update sbt-scoverage to 2.0.5
  project/plugins.sbt
Labels: dependencies

#237 Update scalafmt-core to 3.6.0
  .scalafmt.conf
Labels: dependencies

#229 Update sbt-scalafix to 0.10.4
  project/plugins.sbt
Labels: dependencies

#240 Add play filters logging
  README.md
  build.sbt
  play/filters/logging/src/main/scala/io/kinoplan/utils/play/filters/logging/LoggingFilter.scala
  play/filters/logging/src/main/scala/io/kinoplan/utils/play/filters/logging/RequestMapContext.scala
  play/filters/logging/src/test/resources/application-test-body-size.conf
  play/filters/logging/src/test/resources/application-test-only-successful.conf
  play/filters/logging/src/test/resources/application-test-simple.conf
  play/filters/logging/src/test/resources/logback.xml
  play/filters/logging/src/test/scala-2.12/io/kinoplan/utils/play/filters/logging/kit/ListAppenderSyntax.scala
  play/filters/logging/src/test/scala-2.13/io/kinoplan/utils/play/filters/logging/kit/ListAppenderSyntax.scala
  play/filters/logging/src/test/scala/io/kinoplan/utils/play/filters/logging/LoggingFilterSpec.scala
  project/Dependencies.scala
  project/ModulesPlay.scala
Labels: enhancement

#234 Update scala-library to 2.13.10
  .github/workflows/build.yml
  project/ProjectSettings.scala
Labels: dependencies

#241 Add play error handler
  README.md
  build.sbt
  play/error-handler/src/main/scala/io/kinoplan/utils/play/error/ErrorHandler.scala
  play/error-handler/src/test/resources/application-test-dev.conf
  play/error-handler/src/test/resources/application-test-prod.conf
  play/error-handler/src/test/resources/logback.xml
  play/error-handler/src/test/scala/io/kinoplan/utils/play/error/ErrorHandlerSpec.scala
  play/filters/logging/src/main/scala/io/kinoplan/utils/play/filters/logging/LoggingFilter.scala
  play/filters/logging/src/test/scala/io/kinoplan/utils/play/filters/logging/LoggingFilterSpec.scala
  play/request/map-context/src/main/scala/io/kinoplan/utils/play/request/RequestMapContext.scala
  project/ModulesPlay.scala
Labels: enhancement

#242 Fix withDiagnostic for null error message in play reactivemongo
  play/reactivemongo/src/main/scala/io/kinoplan/utils/play/reactivemongo/ReactiveMongoDaoBase.scala
Labels: bug
