Repository kinoplan/utils, pull requests merged in 2023-01, with the labels that each got.

#273 Add support zio 2
  build.sbt
  project/Dependencies.scala
  zio/monitoring/prometheus/src/main/scala/io/kinoplan/utils/zio/monitoring/prometheus/config/PrometheusConfig.scala
  zio/monitoring/prometheus/src/main/scala/io/kinoplan/utils/zio/monitoring/prometheus/server/PrometheusServer.scala
  zio/reactivemongo/src/main/scala/io/kinoplan/utils/zio/reactivemongo/config/MongoConfig.scala
  zio/reactivemongo/src/main/scala/io/kinoplan/utils/zio/reactivemongo/daos/ReactiveMongoDaoBase.scala
Labels: enhancement

#257 Update scala-java-time, ... to 2.5.0
  project/Dependencies.scala
Labels: dependencies

#276 Update redisson to 3.19.1
  project/Dependencies.scala
Labels: dependencies

#277 Update sbt to 1.8.2
  project/build.properties
Labels: dependencies

#278 Update scalactic to 3.2.15
  project/Dependencies.scala
Labels: dependencies

#279 Update scalatest to 3.2.15
  project/Dependencies.scala
Labels: dependencies

#280 Update play to 2.8.19
  project/Dependencies.scala
Labels: dependencies

#281 Update zio to 2.0.6
  project/Dependencies.scala
Labels: dependencies

#282 Add integration check
  README.md
  build.sbt
  common/integration-check/src/main/scala/io/kinoplan/utils/IntegrationCheck.scala
  project/ModulesCommon.scala
Labels: enhancement

#283 Add zio integration check
  README.md
  build.sbt
  project/ModulesZio.scala
  zio/integration-check/src/main/scala/io/kinoplan/utils/zio/ZIntegration.scala
  zio/integration-check/src/main/scala/io/kinoplan/utils/zio/ZIntegrationCheck.scala
Labels: enhancement

#284 Add integration check support for zio reactivemongo
  build.sbt
  project/ModulesZio.scala
  zio/reactivemongo/src/main/scala/io/kinoplan/utils/zio/reactivemongo/api/IntegrationCheck.scala
  zio/reactivemongo/src/main/scala/io/kinoplan/utils/zio/reactivemongo/api/ReactiveMongoApi.scala
  zio/reactivemongo/src/main/scala/io/kinoplan/utils/zio/reactivemongo/modules/MongoModule.scala
Labels: enhancement

#285 Update scalafmt-core to 3.7.0
  .scalafmt.conf
Labels: dependencies

#286 Add zio http4s healthcheck
  README.md
  build.sbt
  project/Dependencies.scala
  project/ModulesZio.scala
  project/ProjectSettings.scala
  zio/http4s/healthcheck/src/main/scala/io/kinoplan/utils/zio/http4s/Healthcheck.scala
  zio/http4s/healthcheck/src/main/scala/io/kinoplan/utils/zio/http4s/HealthcheckServer.scala
  zio/http4s/healthcheck/src/main/scala/io/kinoplan/utils/zio/http4s/IntegrationHealthcheck.scala
  zio/http4s/healthcheck/src/main/scala/io/kinoplan/utils/zio/http4s/IntegrationHealthcheckServer.scala
  zio/http4s/healthcheck/src/main/scala/io/kinoplan/utils/zio/http4s/config/IntegrationHealthcheckConfig.scala
  zio/http4s/healthcheck/src/main/scala/io/kinoplan/utils/zio/http4s/config/ServerConfig.scala
Labels: enhancement

#287 Refactoring & improve zio monitoring prometheus
  zio/monitoring/prometheus/src/main/scala/io/kinoplan/utils/zio/monitoring/PrometheusConfig.scala
  zio/monitoring/prometheus/src/main/scala/io/kinoplan/utils/zio/monitoring/PrometheusModule.scala
  zio/monitoring/prometheus/src/main/scala/io/kinoplan/utils/zio/monitoring/PrometheusServer.scala
  zio/monitoring/prometheus/src/main/scala/io/kinoplan/utils/zio/monitoring/PrometheusServerApp.scala
  zio/monitoring/prometheus/src/main/scala/io/kinoplan/utils/zio/monitoring/prometheus/modules/PrometheusModule.scala
  zio/monitoring/prometheus/src/main/scala/io/kinoplan/utils/zio/monitoring/prometheus/server/PrometheusServer.scala
Labels: enhancement

#288 Fix redisson codec dependency provided
  project/ModulesCommon.scala
Labels: bug

#291 Update play-json to 2.9.4
  project/Dependencies.scala
Labels: dependencies

#293 Update scalafmt-core to 3.7.1
  .scalafmt.conf
Labels: dependencies

#290 Update jackson-module-scala to 2.14.2
  project/Dependencies.scala
Labels: dependencies
