Repository kinoplan/utils, pull requests merged in 2024-03, with the labels that each got.

#531 Update scala-library to 2.13.13
  .github/workflows/build.yml
  project/ProjectSettings.scala
Labels: dependencies

#534 Update sbt-scalafix to 0.12.0
  project/plugins.sbt
Labels: dependencies

#538 Update tapir-core, tapir-server to 1.9.11
  project/Dependencies.scala
Labels: dependencies

#539 Update http4s-dsl, http4s-server to 0.23.26
  project/Dependencies.scala
Labels: dependencies

#542 Update slf4j-backend to 3.9.4
  project/Dependencies.scala
Labels: dependencies

#544 Replace a SmartIndex key type with Seq instead of Set
  common/reactivemongo/base/src/main/scala/io/kinoplan/utils/reactivemongo/base/SmartIndex.scala
  play/reactivemongo/src/main/scala/io/kinoplan/utils/play/reactivemongo/ReactiveMongoDaoBase.scala
  zio/reactivemongo/src/main/scala/io/kinoplan/utils/zio/reactivemongo/ReactiveMongoDaoBase.scala
Labels: bugfix

#545 Update jackson-module-scala to 2.17.0
  project/Dependencies.scala
Labels: dependencies

#546 Add sbt-shading and shade zio-config dependencies
  project/Dependencies.scala
  project/ModulesCommon.scala
  project/ModulesImplicits.scala
  project/ModulesPlay.scala
  project/ModulesZio.scala
  project/ProjectSettings.scala
  project/plugins.sbt
Labels: build

#502 Update zio-config, zio-config-magnolia, ... to 4.0.1
  project/Dependencies.scala
  zio/http4s/healthcheck/src/main/scala/io/kinoplan/utils/zio/http4s/HealthcheckServer.scala
  zio/http4s/healthcheck/src/main/scala/io/kinoplan/utils/zio/http4s/IntegrationHealthcheck.scala
  zio/http4s/healthcheck/src/main/scala/io/kinoplan/utils/zio/http4s/IntegrationHealthcheckServer.scala
  zio/http4s/healthcheck/src/main/scala/io/kinoplan/utils/zio/http4s/config/IntegrationHealthcheckConfig.scala
  zio/http4s/healthcheck/src/main/scala/io/kinoplan/utils/zio/http4s/config/ServerConfig.scala
  zio/monitoring/prometheus/src/main/scala/io/kinoplan/utils/zio/monitoring/PrometheusConfig.scala
  zio/monitoring/prometheus/src/main/scala/io/kinoplan/utils/zio/monitoring/PrometheusServer.scala
  zio/reactivemongo/src/main/scala/io/kinoplan/utils/zio/reactivemongo/config/MongoConfig.scala
Labels: dependencies

#549 Update sbt-scalajs, scalajs-compiler, ... to 1.16.0
  project/plugins.sbt
Labels: dependencies

#550 Update sbt-shading to 2.1.4
  project/plugins.sbt
Labels: dependencies

#554 Update scalafmt-core to 3.8.1
  .git-blame-ignore-revs
  .scalafmt.conf
  common/redisson/core/src/main/scala/io/kinoplan/utils/redisson/core/operation/RedisArrayOperations.scala
Labels: dependencies

#553 Switch deprecated zio-metrics-prometheus to zio-metrics-connectors wi…
  project/Dependencies.scala
  project/ModulesZio.scala
  scalafix.sbt
  zio/monitoring/prometheus/src/main/scala/io/kinoplan/utils/zio/monitoring/PrometheusModule.scala
  zio/monitoring/prometheus/src/main/scala/io/kinoplan/utils/zio/monitoring/PrometheusServer.scala
  zio/monitoring/prometheus/src/main/scala/io/kinoplan/utils/zio/monitoring/RootConfig.scala
Labels: refactor, feature
